### ISSUE TITLE
Livro disponível online!

### ISSUE THREAD

**Issue by aristidesneto** [caiodelgadonew/docker#3]
Caio, você acha interessante publicar esse conteúdo também online usando por exemplo o Honkit?

Particularmente acho bacana estar disponível online além de estar em PDF seu livro.

Se achar interessante posso contribuir migrando para essa ferramenta.

Vlw

**Comment by caiodelgadonew** [comment]
Opa, fala @aristidesneto , não sei o que pensar sobre o assunto, porque o livro ta disponível aqui pra leitura, se você navegar no readme a leitura também é possível.

**Comment by aristidesneto** [comment]
Tranquilo entendo, seria mais para facilitar a navegação mesmo, pois por aqui não é tão fluído assim...

**Comment by caiodelgadonew** [comment]
O problema maior seria manter mais um ponto, e distribuir essa atualização.

Vou fechar aqui a issue :)
