### ISSUE TITLE
Sugestão de renomeação do nó master para main no vagrant

### ISSUE THREAD

**Issue by kessix** [caiodelgadonew/docker#7]
@caiodelgadonew como já vem sendo adotado a não utilização de termologias atrasadas, sugiro a renomeação do hostname da vm master para main, ou outro termo mais adequado.

**Comment by caiodelgadonew** [comment]
Opa @kessix , não se utiliza a nomenclatura main para este caso, o correto seria manager. 

Caso queira pode abrir um PR com as mudanças que eu aprovo e faço o merge, no momento não estou com tempo hábil (nós próximos 2 meses) para modificar

**Comment by kessix** [comment]
Beleza @caiodelgadonew, vou abrir um PR.

**Comment by caiodelgadonew** [comment]
Boa!
